In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import StandardScaler 
from time import time 

In [2]:
np.random.seed(1337)

In [3]:
df = pd.read_csv("/home/lucas/Documents/ia-lucas-dados/dados/DeepLearningI/Cap02/titanic.csv")

In [4]:
df.head()

Survived  Class  Sex   Age     Fare
0         0      3    1  22.0   7.2500
1         1      1    0  38.0  71.2833
2         1      3    0  26.0   7.9250
3         1      1    0  35.0  53.1000
4         0      3    1  35.0   8.0500

In [5]:
df.shape

(891, 5)

In [6]:
df_train = df.iloc[:712, :]

# Padronizando os dados
scaler = StandardScaler()
features = ['Class', 'Sex', 'Age', 'Fare']

x_train = scaler.fit_transform(df_train[features].values)
y_train = df_train['Survived'].values
print(x_train, y_train)

[[ 0.83290956  0.74926865 -0.61259594 -0.51933199]
 [-1.55353553 -1.33463478  0.6184268   0.79718222]
 [ 0.83290956 -1.33463478 -0.30484025 -0.5054541 ]
 ...
 [ 0.83290956  0.74926865 -0.02023413 -0.35493964]
 [-1.55353553 -1.33463478 -0.45871809  0.34940748]
 [-1.55353553  0.74926865 -0.02023413 -0.12252713]] [0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 

In [7]:
y_train_onehot = pd.get_dummies(df_train['Survived']).values
print(y_train_onehot)

[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]


In [8]:
df_test = df.iloc[712:, :]

x_test = scaler.transform(df_test[features].values)
y_test = df_test['Survived'].values

# Criando um modelo com Arvore de Decisao (Benchmarking)

In [9]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=0, verbose=3)
model = model.fit(x_train, df_train['Survived'].values)

y_prediction = model.predict(x_test)
print(y_prediction==y_test)
print(float(len(y_test)))
print("\nAcuracia", np.sum(y_prediction==y_test)/float(len(y_test)))

building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
b

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


# Rede Neural com 1 Camada 

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Activation

start = time()

model = Sequential()

model.add(Dense(input_dim=4, units=2))
model.add(Activation("softmax"))

model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

model.fit(x_train, y_train_onehot)

print("\nTempo gasto %s segundos" % str(time()-start))

23/23 [==============================] - 0s 534us/step - loss: 0.7495 - accuracy: 0.6531

Tempo gasto 3.1227660179138184 segundos


In [11]:
y_prediction = model.predict_classes(x_test)
print("\n\nAcuracia:", np.sum(y_prediction==y_test)/float(len(y_test)))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


Acuracia: 0.7039106145251397


# Rede Neural com 2 Camadas

In [12]:
from keras.models import Sequential
from keras.layers import Dense, Activation

start = time()

model = Sequential()

model.add(Dense(input_dim=4, units=100))
model.add(Dense(units=2))
model.add(Activation("softmax"))

model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

model.fit(x_train, y_train_onehot)

print("\nTempo gasto %s segundos" % str(time()-start))

23/23 [==============================] - 0s 423us/step - loss: 0.7618 - accuracy: 0.4185

Tempo gasto 0.24007010459899902 segundos


In [13]:
y_prediction = model.predict_classes(x_test)
print("\n\nAcuracia:", np.sum(y_prediction==y_test)/float(len(y_test)))



Acuracia: 0.8044692737430168


# Rede Neural com 3 Camadas

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Activation

start = time()

model = Sequential()

model.add(Dense(input_dim=4, units=100))
model.add(Dense(units=100))
model.add(Dense(units=2))
model.add(Activation("softmax"))

model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

model.fit(x_train, y_train_onehot)

print("\nTempo gasto %s segundos" % str(time()-start))

23/23 [==============================] - 0s 559us/step - loss: 0.6467 - accuracy: 0.6545

Tempo gasto 0.2679450511932373 segundos


In [15]:
y_prediction = model.predict_classes(x_test)
print("\n\nAcuracia:", np.sum(y_prediction==y_test)/float(len(y_test)))



Acuracia: 0.7597765363128491
